[project]
authors = ["Alejandro Castellanos <k2jac9@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "ai_dev_env"
platforms = ["win-64"]
version = "0.1.0"

[dependencies]
adbc-driver-manager = "*"
azure-identity = "*"
boto3 = "*"
connectorx = "*"
cookiecutter = "*"
dask = "*"
deltalake = "*"
duckdb = "*"
evidently = "*"
fancyimpute = "*"
fastapi = "*"
fastparquet = "*"
google-auth = "*"
h5py = "*"
ipykernel = "*"
ipywidgets = "*"
jupyter = "*"
jupyter_server = "*"
jupyterlab = "*"
kaggle = "*"
kagglehub = "*"
matplotlib = "*"
metaflow = "*"
missingno = "*"
mlflow = "*"
modin = "*"
nbclient = "*"
nbconvert = "*"
nbformat = "*"
notebook = "*"
numpy = "*"
opencv = "*"
openpyxl = "*"
opentofu = "*"
optuna = "*"
optuna-dashboard = "*"
pandas = "*"
pango = "*"
plotly = "*"
polars = "*"
psycopg2 = "*"
pyarrow = "*"
pybind11 = "*"
pydantic = "*"
pygam = "*"
pyiceberg = "*"
python = "3.12.*"
python-dotenv = "*"
requests = "*"
ruff = "*"
sacred = "*"
scikit-image = "*"
scikit-learn = "*"
seaborn = "*"
shap = "*"
sqlalchemy = "*"
streamlit = "*"
tqdm = "*"
transformers = "*"
uv = "*"
xgboost = "*"
yfinance = "*"

[pypi-dependencies]
featureform = "*"
torch = "*"
torchaudio = "*"
torchvision = "*"

[pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://download.pytorch.org/whl/cpu"]

[tasks]
install-tf-cpu = "uv pip install tensorflow-cpu==2.19"

run-flow = { cmd = "python src/flows/bdyfat_flow.py run" }
